# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  database:
     image: postgres:latest
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=postgres
     ports:
       - "5432:5432"
     restart: unless-stopped
     volumes:
       - database-data:/var/lib/postgresql/data
    
  pgadmin:
     image: dpage/pgadmin4
     environment:
       - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
       - PGADMIN_DEFAULT_PASSWORD=admin2
     ports:
        - "5050:80" 
       # reverse proxying
     restart: unless-stopped
     volumes:
       - pgadmin:/root/.pgAdmin

  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on: 
       - database

volumes:
  database-data:
  pgadmin:
